In [1]:
import numpy as np
import random

In [4]:
a = np.ones([3,3])
b = np.random.randint(0,3,(3,3))
print(a)
print(b)
b[1,1] = 2
print(b)
c = b[:,1]
print(c)
d = np.empty(3)
print(d)
print(np.sum(b))
e = b[b == 0]
print(e)
f = [1,3,5,2,5]
g = f.index(max(f))
print(g)
print(np.max(b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 0 1]
 [1 0 0]
 [0 2 1]]
[[1 0 1]
 [1 2 0]
 [0 2 1]]
[0 2 2]
[ 0. 17. 12.]
8
[0 0 0]
2
2


In [22]:
c = (b > 0) * 1.0
print(c)
print(np.dot(a,b))
print(np.sum(b))
print(c[:,1])
d = [[0,0,0]]
e = np.insert(d,1,values=[[0,1,2]],axis=0)
print(e)
print([1,1,1]==[1,1,1])
print(np.size(e,1))
f = e[0,:]
print(f[0])
print(1/2)

[[0. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 5. 3.]
 [3. 5. 3.]
 [3. 5. 3.]]
11
[1. 1. 1.]
[[0 0 0]
 [0 1 2]]
True
3
0
0.5


In [8]:
import torch    # 如正常则静默
a = torch.Tensor([1.])    # 如正常则静默
a.cuda()    # 如正常则返回"tensor([ 1.], device='cuda:0')"
from torch.backends import cudnn # 如正常则静默
cudnn.is_acceptable(a.cuda())    # 如正常则返回 "True"

OSError: /root/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory

In [44]:
a = np.array([[1,0,2,3,7],[1,2,3,1,1],[6,4,5,2,1]])
np.save('try_data.npy',a)

In [45]:
b = np.load('try_data.npy')
b[1,4] = None
print(b)

np.save('try_data.npy',b)
data_c = np.load('try_data.npy')
print(data_c)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [83]:
x = np.array([1,2,3])
x = np.append(x,[4,5])
print(x)

[1 2 3 4 5]


In [85]:
a = np.zeros([1,18])
np.save('train_data.npy',a)

In [120]:
x = np.load('train_data.npy')
for i in range(np.size(x,0)):
    if x[i,17]>8:
        print(x[i])


[ 4.          4.          0.          0.          4.          0.
  0.          0.          2.          0.          0.          0.
  0.          0.          0.          0.         49.77777778  9.        ]
[ 4.   4.   0.   0.   4.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.  76.8 15. ]
[ 4.  4.  0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 56. 10.]
[ 4.          4.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  4.          0.          0.          0.         59.63636364 22.        ]
[ 4.          4.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  2.          0.          0.          0.         69.33333333  9.        ]
[ 4.  2.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 64. 10.]
[ 4.          2.          0.          0.          4.          0.
  0.          0.          4.          0.          0.          0.
  4.          0.  

  4.          0.          0.          0.         63.27272727 22.        ]
[ 4.          0.          0.          0.          0.          0.
  0.          0.          0.          2.          0.          0.
  4.          0.          0.          0.         62.54545455 22.        ]
[ 4.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          4.          0.
  4.          0.          0.          0.         76.63157895 19.        ]
[ 4.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          2.          0.
  4.          0.          0.          0.         54.28571429 28.        ]
[ 4.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          4.
  4.          0.          0.          0.         58.66666667 12.        ]
[ 4.          0.          0.          0.          0.          0.
  0.          0.          0.          0.     

[ 0.  0.  0.  4.  4.  0.  0.  0.  4.  0.  0.  0.  2.  0.  0.  0. 48.  9.]
[ 0.          0.          0.          4.          4.          0.
  0.          0.          2.          0.          0.          0.
  4.          0.          0.          0.         56.88888889  9.        ]
[ 0.          0.          0.          4.          4.          0.
  0.          0.          0.          0.          0.          0.
  4.          0.          0.          0.         69.33333333 12.        ]
[ 0.   0.   0.   4.   0.   0.   0.   4.   0.   0.   0.   4.   0.   0.
  0.   4.  59.2 10. ]
[ 0.          0.          0.          4.          0.          0.
  0.          4.          0.          0.          0.          0.
  0.          0.          0.          2.         60.44444444  9.        ]
[ 0.  0.  0.  4.  0.  0.  0.  2.  0.  0.  0.  2.  0.  0.  0.  0. 57. 16.]
[ 0.  0.  0.  4.  0.  0.  0.  0.  0.  0.  0.  4.  0.  0.  0.  2. 64. 12.]
[ 0.   0.   0.   4.   0.   0.   0.   0.   0.   0.   0.   2.   2.   0.
  0.

  4.          2.          0.          0.         58.10526316 19.        ]
[ 0.   0.   0.   0.   2.   0.   0.   0.   0.   0.   0.   0.   4.   0.
  4.   0.  76.8 10. ]
[ 0.   0.   0.   0.   2.   0.   0.   0.   0.   0.   0.   0.   4.   0.
  2.   0.  59.2 20. ]
[ 0.          0.          0.          0.          2.          0.
  0.          0.          0.          0.          0.          0.
  4.          0.          0.          4.         67.36842105 19.        ]
[ 0.          0.          0.          0.          2.          0.
  0.          0.          0.          0.          0.          0.
  4.          0.          0.          2.         53.33333333  9.        ]
[ 0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  2.  0.  0.  2. 72. 10.]
[ 0.          0.          0.          0.          0.          4.
  0.          0.          8.          0.          0.          0.
  8.          4.          0.          0.         42.66666667  9.        ]
[ 0.          0.          0.          0.          0.    

  8.          2.          4.          0.         66.66666667 12.        ]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  8.          2.          0.          2.         66.28571429 14.        ]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  8.          0.          2.          4.         35.55555556  9.        ]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  4.          4.          4.          2.         56.88888889  9.        ]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  4.          4.          2.          4.         71.11111111  9.        ]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.     

In [100]:
x = np.delete(x,-1,axis=0)
print(x)

[[32.  4.  0.  0.  8.  8.  4.  0.  2. 16.  0.  0.  0.  2.  0.  0. 64.  1.]
 [32.  4.  0.  0.  4.  8.  0.  0.  4. 16.  0.  0.  2.  2.  0.  0. 64.  1.]
 [ 8. 64.  4.  4.  4.  4. 16.  0.  8.  0.  4.  0.  0.  0.  0.  0. 64.  1.]
 [ 8. 32.  8.  2.  4. 16. 64.  0.  2.  8.  2.  2.  4.  0.  0.  0. 64.  1.]
 [ 8. 32.  8.  2.  0.  4. 16. 64.  2.  0.  8.  2.  0.  0.  0.  4. 64.  1.]
 [ 8.  8. 16.  4.  2.  2.  4.  4.  8.  8.  0.  0.  2.  0.  0.  0. 64.  1.]
 [ 8.  4.  2.  8.  4. 32.  8.  2.  2. 16. 64.  4.  4.  8.  2.  4. 64.  2.]
 [ 8.  4.  2.  4.  4. 32.  8.  4.  2. 16. 64.  2.  4.  8.  2.  4. 64.  1.]
 [ 8.  4.  2.  4.  4. 32.  8.  0.  2. 16. 64.  2.  4.  8.  2.  4. 64.  1.]
 [ 8.  4.  0.  4.  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0. 64.  1.]
 [ 8.  0.  4.  2.  4. 32.  8.  0.  2. 16. 64.  2.  4.  8.  2.  4. 64.  1.]
 [ 8.  0.  4.  0.  4. 32.  8.  0.  2. 16. 64.  2.  4.  8.  2.  4. 64.  1.]
 [ 8.  0.  4.  0.  4.  0.  0.  0.  4. 32. 16.  0.  4. 32.  4.  2. 64.  1.]
 [ 8.  0.  0.  2.  2.  8.

In [6]:
import itertools
def pairwise(iterable):
    "s -> (s0,s1), (s1,s2), (s2, s3), ..."
    a, b = itertools.tee(iterable)
    print([a,b])
    next(b, None)
    return zip(a, b)

print(pairwise([1,2,3]))

[<itertools._tee object at 0x7fbd70492e08>, <itertools._tee object at 0x7fbd70492e48>]


In [21]:
flat=np.array([[1,2],[3,4]])
print(np.repeat(flat[:,:,np.newaxis], 16, axis=-1))

[[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]

 [[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]]]


In [22]:
from game2048.game import Game
from game2048.displays import Display, IPythonDisplay
from game2048.agents import Agent, RandomAgent2, ExpectiMaxAgent,YourOwnAgent

In [23]:
display1 = Display()
display2 = IPythonDisplay()

In [ ]:
def single_run(size, score_to_win, AgentClass, **kwargs):
    game = Game(size, score_to_win)
    agent = AgentClass(game, display=None, **kwargs)
    agent.play(verbose=True)
    return game.score


if __name__ == '__main__':
    GAME_SIZE = 4
    SCORE_TO_WIN = 2048
    N_TESTS = 10

    '''====================
    Use your own agent here.'''
    from game2048.agents import YourOwnAgent as TestAgent
    '''===================='''

    scores = []
    for _ in range(N_TESTS):
    #score = 0
    #while score < 512:
        score = single_run(GAME_SIZE, SCORE_TO_WIN,
                           AgentClass=TestAgent)
        print('score:',score)
        scores.append(score)

    print("Average scores: @%s times" % N_TESTS, sum(scores) / len(scores))

Iter: 1
======Direction: right======
Iter: 2
======Direction: left======
Iter: 3
======Direction: left======
Iter: 4
======Direction: left======
Iter: 5
======Direction: left======
Iter: 6
======Direction: down======
Iter: 7
======Direction: right======
Iter: 8
======Direction: left======
Iter: 9
======Direction: right======
Iter: 10
======Direction: down======
Iter: 11
======Direction: down======
Iter: 12
======Direction: left======
Iter: 13
======Direction: right======
Iter: 14
======Direction: up======
Iter: 15
======Direction: down======
Iter: 16
======Direction: up======
Iter: 17
======Direction: up======
Iter: 18
======Direction: down======
Iter: 19
======Direction: up======
Iter: 20
======Direction: right======
Iter: 21
======Direction: down======
Iter: 22
======Direction: left======
Iter: 23
======Direction: left======
Iter: 24
======Direction: up======
Iter: 25
======Direction: right======
Iter: 26
======Direction: left======
Iter: 27
======Direction: right======
Iter: 28
====

In [1]:
import numpy as np
import random
from game2048.features import Feature
import game2048.agents
f = Feature()
x = np.array([[0,0,16,16],[0,0,2,4],[0,0,0,0],[0,0,0,0]])
print(f.feature(x))
y = []
y = np.append(y,f.feature(x),axis = 0)
y1 = np.append(y,f.feature(x))
print(y1)
y2 = np.append([y],[y],axis = 0)
print(y2)
y3 = np.append(y2,[f.feature(x)],axis = 0)
print(y3)
z = f.simplify(x)

(0.0, 17, 12)
[ 0. 17. 12.  0. 17. 12.]
[[ 0. 17. 12.]
 [ 0. 17. 12.]]
[[ 0. 17. 12.]
 [ 0. 17. 12.]
 [ 0. 17. 12.]]
{2: 1, 4: 2, 8: 3, 16: 4, 32: 5, 64: 6, 128: 7, 256: 8, 512: 9, 1024: 10, 0: 0}


In [33]:
a = np.array([[0,22,15,0,21,14,0,22,15,0,21,14]])
b = np.array([0])
np.savez('train_data_fit.npz',data = a,label = b)

In [15]:
a = np.array([[0,0,0,0,0,0,0,0,0,0,1,0,0,2,0,2]])
b = np.array([1])
np.savez('epoch64_fit.npz',data = a,label = b)
a = np.array([[0,1,0,0,2,3,2,0,4,1,0,1,7,2,3,2]])
b = np.array([0])
np.savez('epoch128_fit.npz',data = a,label = b)
a = np.array([[0,0,1,0,1,3,2,0,2,1,2,3,8,4,0,0]])
b = np.array([0])
np.savez('epoch256_fit.npz',data = a,label = b)
a = np.array([[3,0,0,0,1,2,0,0,3,2,4,0,9,4,0,0]])
b = np.array([1])
np.savez('epoch512_fit.npz',data = a,label = b)
a = np.array([[10,4,2,4,0,1,1,0,0,0,0,0,0,1,0,0]])
b = np.array([3])
np.savez('epoch1024_fit.npz',data = a,label = b)

In [32]:
download = np.load('epoch256_fit.npz')
#print(download['data'])
print(np.size(download['label']))

150


In [26]:
a = np.array([[0,0,0,0,0,0,0,0,0,0,1,0,0,2,0,2]])
b = np.array([1])
np.savez('epoch64_fit.npz',data = a,label = b)